### ISSUE TITLE
网页图片一直在读取

### ISSUE THREAD

**Issue by nimrod1990** [linyuxuanlin/Gallery-Portfolio#4]
Vercel部署，请问如何查找哪里出了问题🤔

**Comment by blackvon-sudo** [comment]
我也是这样，还没找到问题

**Comment by blackvon-sudo** [comment]
找到问题了，添加API Tokens时，要勾选倒数第二项，可读写的那一个权限，因为要创建缩略图的，需要写入权限

**Comment by nimrod1990** [comment]
> 找到问题了，添加API Tokens时，要勾选倒数第二项，可读写的那一个权限，因为要创建缩略图的，需要写入权限

我勾选的就是倒数第二项🥲

**Comment by linyuxuanlin** [comment]
对，创建缩略图需要写入权限。
如果一直在读取，可以打开网页开发者工具 - 网络，如果没有提示报错，请等一下，创建缩略图比较耗时。

**Comment by nimrod1990** [comment]
> 对，创建缩略图需要写入权限。
> 如果一直在读取，可以打开网页开发者工具 - 网络，如果没有提示报错，请等一下，创建缩略图比较耗时。

感谢，如果能做到图片分类显示就更好。
